### ISSUE TITLE
[epic] VS Code Plugin: Support validating schema from a running Jenkins instance

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1077]
It would be great to have a VS Code plugin which automatically fetches JSON Schema from a running instance so that users can easily integrate the feature in their flows.

Acceptance criteria:

- [x] There is a new "JCasC plugin" for VS Code. It should be a new repository under jenkinsci (will need to pass through the hosting process)
- [x] The plugin can fetch (and cache?) JSON Schema using REST API from JCasC instances
- [x] It is possible to configure the plugin in project settings:
  * Jenkins URL
  * User / API Token
- [x] Once configured, the plugin automatically applies the JSON schema to `jenkins.yaml` files or other JCasC files (TBD: how to locate them? project settings)
- [ ] JCasC IDE Integration page is updated to reference the plugin
- [ ] There is some smoke test automation
- [x] There is some CI configured for the new repository, preferably Jenkinsfile
- [x] The plugin is released and hosted on the VS Code Marketplace
- [x] There is a blogpost on jenkins.io for the new plugin
- [x] The JCasC Dev Tools project page is updated

**Comment by timja** [comment]
Supported now https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/jsonSchema.md
